import { createLogger } from '../logger'
import { barionPost, getBarionConfig, type BarionClientConfig } from './client'
import { canonicalBarionGuid, canonicalizeBarionGuid } from './guid'
import {
  BarionApiError,
  type BarionAccountCreationIndicator,
  type BarionBillingAddress,
  type BarionItem,
  type BarionPayerAccountInformation,
  type BarionPaymentStartRequest,
  type BarionPaymentStartResponse,
  type BarionPaymentTransaction,
  type BarionPurchaseInformation,
} from './types'

/**
 * Payment/Start v2 — új azonnali (Immediate) fizetés indítása a Barionban.
 *
 * Fix üzleti szabályok (a lib állítja, a hívó nem felülírható módon kapja):
 * - PaymentType: Immediate (előleg/részletfizetés nincs)
 * - GuestCheckOut: true (Barion-fiók nélkül is fizethet a vevő). A
 *   barion-web-php v3.0.0 (2026-06-17) kivette a mezőt a saját modelljéből, a
 *   Payment-Start-v2 doksi (2026-01-07) viszont továbbra is „Required"-ként
 *   írja le; amíg a doksi nem ejti, küldjük.
 * - FundingSources: ['All']
 * - Locale: 'hu-HU', Currency: 'HUF'
 * - PaymentWindow: default '00:30:00' (paraméterezhető)
 * - PaymentRequestId: a rendelés orderNumber-e (pl. KH-2026-000123). A Barion
 *   doksija szerint ez CSAK azonosító a bolt saját nyilvántartásához és a havi
 *   kivonathoz („The unique identifier for the payment generated by the shop.
 *   This is so the shop can track its own payment identifiers."); a Barion
 *   NEM dokumentál hozzá deduplikációt, tehát egy ismételt Start ugyanazzal a
 *   PaymentRequestId-vel ÚJ fizetést hozhat létre. A Start ezért sosem fut
 *   újra automatikusan (start-checkout.ts: bizonytalan kimenetnél a rendelés
 *   payment_pending marad a fizetési ablak végéig). Az Idempotency-Key fejléc
 *   (csak a PHP SDK-ban dokumentált) tudatosan HALASZTVA: az újrajátszás
 *   élettartama és a 409/422 viselkedése nincs leírva.
 * - OrderNumber: szintén az orderNumber (opcionális mező, a havi kivonaton és
 *   a tranzakció-exportban is megjelenik, Payment-Start-v2).
 *
 * Összegszámítás NINCS a libben: a tranzakciók Total/ItemTotal értékeit a
 * hívó adja, szerver-oldalon validálva (az orders snapshot-árai a forrás).
 *
 * 3DS-adatok (BillingAddress, PurchaseInformation, PayerAccountInformation,
 * ChallengePreference): a Payment-Start-v2 szerint „if the merchant does not
 * provide 3DS-related properties, it doesn't mean that the payment will fail.
 * It means that the payer will have a higher chance of getting a challenge
 * during payment." Digitális kurzusnál a vevőnek nem kell kihívást kapnia
 * csak azért, mert semmit nem küldtünk. Egy ROSSZ érték viszont minden
 * Startot elutasíttatna (ModelValidationError), vagyis minden eladás megállna.
 * Ezért minden mezőnév, enum-érték és hosszkorlát két forrásból ellenőrzött:
 * a docs.barion.com oldalai (Wayback: Payment-Start-v2 20260122015633,
 * BillingAddress 20241110122232, PurchaseInformation 20260122003811,
 * PayerAccountInformation 20241110113244, DeliveryTimeframeType
 * 20241014080354, ShippingAddressIndicator 20241014091045, PurchaseType
 * 20241014092043, ChallengePreference 20260122020254) és a hivatalos
 * barion-web-php modelljei és enumerációi (Models/Payment/
 * PreparePaymentRequestModel, Models/ThreeDSecure/*, Enumerations/ThreeDSecure/*).
 * Amit nem tudunk bizonyítottan helyes értékkel kitölteni, az kimarad (pl.
 * Region, ReOrderIndicator, telefonszám). A BARION_SEND_3DS='false'
 * vészkapcsoló a négy 3DS-blokkot hagyja ki (az OrderNumbert nem), lásd
 * `barionSend3dsEnabled`. Az élesítés a tulajdonossal egyeztetett idősávban
 * történik, élő próbával (sandbox-kártyánál a 3DS nem fut): két, legalább
 * 10 Ft-os (`BARION_MIN_TRANSACTION_HUF`) termékre indított, a Barion-oldalon
 * fizetés nélkül otthagyott Payment/Start, egy vendégként és egy
 * bejelentkezett vevőként, mert a PayerAccountInformation a kettőben más
 * (NoAccount, illetve AccountId + AccountCreated + a fiók korának sávja). Ez
 * 0 Ft-ba kerül, és mindkét vevőtípus body-ját élőben ellenőrzi, mert a
 * ModelValidationError magából a Startból jön vissza; a fiók korának többi
 * sávját (amelybe a próbafiók nem esik) csak a fenti két forrás igazolja. A
 * próbavevővel (e-mail-cím, illetve fiók) az előző 30 percben
 * (BARION_DEFAULT_PAYMENT_WINDOW) nem indulhatott fizetés ugyanarra a
 * kurzusra: egyező adatoknál a pénztár a még nyitott fizetést folytatja
 * (start-checkout.ts, resolveDuplicatePurchase: 'resume'), új Start nem megy
 * ki, a Barion-oldal mégis megnyílik, és a próba sikeresnek látszana. Ezért a
 * runbook azt is ellenőrizteti, hogy mindkét próbához új rendelés jött létre.
 * A kihívás-ág (challenge) ellenőrzéséhez ezt követheti egy valódi, legalább
 * 10 Ft-os kártyás vásárlás és annak visszatérítése a Kineticare adminjából.
 *
 * Recurring-előkészítés (jövőbeli tokenfizetés): az InitiateRecurrence és a
 * RecurrenceId csak akkor kerül a kérésbe, ha a BARION_RECURRING_ENABLED
 * feature-flag 'true' ÉS a hívó kéri. Flag nélkül a recurring-paraméter
 * megadása hibát dob — így nem maradhat észrevétlen, hogy a recurring
 * ténylegesen ki van kapcsolva.
 */

export const BARION_DEFAULT_PAYMENT_WINDOW = '00:30:00'

/**
 * A Barion kártyás fizetés alsó összeghatára forintban. Forrás:
 * docs.barion.com/Troubleshooting (Wayback 20250501171625): „Bank card
 * payments do not work with very small amounts … HUF: 10 HUF or more", és
 * Responsive_web_payment (Wayback 20241014085536), „Minimum amounts": HUF
 * 10 Ft, „In case the payment is prepared with less amount, the customer
 * won't be able to pay it." A pénztár ennél kisebb végösszegnél a rendelés
 * létrehozása ELŐTT elutasít (a-cms-2: a plugin ár-mezője a magyar „4.990"
 * alakot 5 Ft-ként tárolja).
 */
export const BARION_MIN_TRANSACTION_HUF = 10

/** Egy tétel a Start-tranzakcióban (camelCase, a lib képezi a Barion Itemre). */
export interface StartPaymentItemInput {
  name: string
  description: string
  quantity: number
  unit: string
  unitPrice: number
  itemTotal: number
  sku?: string
}

/** Egy tranzakció a Start-kérésben. A total szerver-oldalon validált végösszeg. */
export interface StartPaymentTransactionInput {
  posTransactionId: string
  /** A kedvezményezett Barion e-mail-címe — alapból a konfigurált BARION_PAYEE_EMAIL. */
  payee?: string
  total: number
  comment?: string
  items: StartPaymentItemInput[]
}

/** Recurring-előkészítés paraméterei — csak BARION_RECURRING_ENABLED mellett aktív. */
export interface StartPaymentRecurringInput {
  /** true = a fizetés egyben recurring-szerződés kezdeményezése is. */
  initiateRecurrence: boolean
  /** Külső (kereskedőoldali) recurring-azonosító; initiateRecurrence esetén kötelező. */
  recurrenceId?: string
}

/**
 * 3DS: számlázási cím a pénztár validált adataiból (camelCase, a lib vág és
 * képez). Az országkód CSAK 'HU' vagy 'ZZ' lehet: a pénztár ma kizárólag
 * magyar címet fogad el (K11), a 'ZZ' a docs szerinti „nem tudjuk" érték
 * („If you are not able to provide the billing address, send ZZ").
 */
export interface StartPaymentBillingAddressInput {
  country: 'HU' | 'ZZ'
  city: string
  zip: string
  /** A teljes utca + házszám; a lib 50 karakteres sorokra bontja (Street, Street2, Street3). */
  street: string
}

/**
 * 3DS: a vevő fiókja a bolt rendszerében. Vendégnél `{ kind: 'guest' }`
 * (AccountCreationIndicator: NoAccount); bejelentkezett vevőnél a fiók
 * azonosítója és létrehozási ideje. Érvénytelen vagy hiányzó létrehozási
 * időnél csak az AccountId megy ki.
 */
export type StartPaymentPayerAccountInput =
  { kind: 'guest' } | { kind: 'account'; accountId: string; accountCreated: Date | null }

/** 3DS-adatok a Start-kéréshez; hiányában (vagy kikapcsolt vészkapcsolónál) a 3DS-blokkok kimaradnak. */
export interface StartPaymentThreeDsInput {
  billingAddress: StartPaymentBillingAddressInput
  /** A vevő e-mail-címe (a digitális kézbesítés címzettje, DeliveryEmailAddress). */
  deliveryEmailAddress: string
  /** A vásárlás pillanata; UTC-ben, `Z` nélkül megy ki (PurchaseDate). */
  purchaseDate: Date
  payerAccount: StartPaymentPayerAccountInput
}

export interface StartPaymentParams {
  /** A rendelés orderNumber-e (KH-YYYY-NNNNNN) — ez lesz a Barion PaymentRequestId. */
  paymentRequestId: string
  /** A rendelésszám az OrderNumber mezőbe (opcionális; a kivonaton és az exportban látszik). */
  orderNumber?: string
  redirectUrl: string
  callbackUrl: string
  transactions: StartPaymentTransactionInput[]
  payerHint?: string
  cardHolderNameHint?: string
  /** hh:mm:ss formátum; alapértelmezés: BARION_DEFAULT_PAYMENT_WINDOW. */
  paymentWindow?: string
  recurring?: StartPaymentRecurringInput
  /**
   * 3DS-adatok. A `buildPaymentStartRequest` maga dönt a vészkapcsolóról
   * (`barionSend3dsEnabled`), a hívó mindig átadhatja.
   */
  threeDs?: StartPaymentThreeDsInput
}

/**
 * A Barion mezőkorlátai. A CardHolderNameHint „Between 2 and 45 characters"
 * (docs.barion.com/Payment-Start-v2). Az Item-mezők korlátja a
 * docs.barion.com/Item oldalon van, amely ellenőrizhetően nem volt elérhető;
 * ezért óvatos felső korlátot alkalmazunk (név 250, leírás 500, SKU 100
 * karakter), és üres leírás helyett a tétel nevét küldjük. A korláton túli
 * mező miatt a Barion az egész fizetésindítást elutasítaná.
 */
export const BARION_CARD_HOLDER_NAME_MIN = 2
export const BARION_CARD_HOLDER_NAME_MAX = 45
export const BARION_ITEM_NAME_MAX = 250
export const BARION_ITEM_DESCRIPTION_MAX = 500
export const BARION_ITEM_SKU_MAX = 100

/**
 * OrderNumber: „Maximum length: 100 characters" (Payment-Start-v2). A
 * BillingAddress korlátai a docs.barion.com/BillingAddress oldalról: City
 * „Maximum 50 characters", Zip „Maximum 16 characters", Street/Street2/Street3
 * „Maximum 50 characters". Az AccountId „Max length 64 characters"
 * (docs.barion.com/PayerAccountInformation).
 */
export const BARION_ORDER_NUMBER_MAX = 100
export const BARION_BILLING_CITY_MAX = 50
export const BARION_BILLING_ZIP_MAX = 16
export const BARION_BILLING_STREET_MAX = 50
export const BARION_BILLING_STREET_LINES = 3
export const BARION_ACCOUNT_ID_MAX = 64

/** Folyamatonként egyszer: a Start minden hívása olvassa a kapcsolót. */
let unrecognisedSend3dsWarned = false

function warnUnrecognisedSend3dsOnce(): void {
  if (unrecognisedSend3dsWarned) {
    return
  }
  unrecognisedSend3dsWarned = true
  // Az értéket nem naplózzuk: egy rossz helyre másolt titok is lehet.
  createLogger({ module: 'barion' }).warn(
    'A BARION_SEND_3DS értéke nem ismert, ezért a 3DS-adatok küldése bekapcsolva marad. Kikapcsolni kizárólag a „false” érték tudja.',
    { envKey: 'BARION_SEND_3DS', effective3ds: true },
  )
}

/**
 * A 3DS-blokkok vészkapcsolója (BARION_SEND_3DS). Alapból BE; kizárólag a szó
 * szerinti 'false' kapcsolja ki (kis-nagybetű és szóköz mindegy). A többi
 * Barion-kulcsot a client.ts `getBarionConfig` olvassa, és az src/env.ts
 * ellenőrzi; ez a kapcsoló helyben olvas (a két fájl más csomag tulajdona), és
 * minden Startnál újra, tehát egy élesben elutasított 3DS-kérés (a RIASZTÁS
 * ModelValidationError-t mutat) egyetlen változó átírásával visszaállítható
 * a korábbi, 3DS nélküli kérésre.
 *
 * A szigorú értelmezés szándékos (a BARION_RECURRING_ENABLED is pontos
 * egyezést vár): a '0', 'off', 'no', 'ki', 'nem' NEM kapcsol ki. Hogy egy
 * ilyen, félreértett érték ne maradjon néma, a nem üres, se 'true', se
 * 'false' értékre a folyamat egyszer figyelmeztet a naplóban (a 3DS ilyenkor
 * bekapcsolva marad). Az üzemeltetői útmutató:
 * docs/uzemeltetes/11-riasztas-es-ugyelet.md („A 3DS-vészkapcsoló”).
 */
export function barionSend3dsEnabled(env: NodeJS.ProcessEnv = process.env): boolean {
  const raw = env.BARION_SEND_3DS
  const normalized = typeof raw === 'string' ? raw.trim().toLowerCase() : ''
  if (normalized !== '' && normalized !== 'true' && normalized !== 'false') {
    warnUnrecognisedSend3dsOnce()
  }
  return normalized !== 'false'
}

/** Egysoros, összevont szóközű szöveg, legfeljebb `max` karakter (Unicode-karakterben mérve). */
function fitText(value: string, max: number): string {
  const normalized = value.replace(/\s+/g, ' ').trim()
  const chars = Array.from(normalized)
  return chars.length <= max ? normalized : chars.slice(0, max).join('').trimEnd()
}

/** A kártyabirtokos-név javaslata a Barion 2–45 karakteres korlátján belül; rövidebbre nincs javaslat. */
export function cardHolderNameHintFor(name: string | undefined): string | undefined {
  if (name === undefined) {
    return undefined
  }
  const hint = fitText(name, BARION_CARD_HOLDER_NAME_MAX)
  return Array.from(hint).length < BARION_CARD_HOLDER_NAME_MIN ? undefined : hint
}

/**
 * Legfeljebb `max` UTF-16 kódegység, kódpont közepén nem vágva. A Barion .NET
 * alapú, a „Maximum N characters" ott a string hossza (UTF-16); a magyar
 * ékezetes betűk egy egységnyiek, de egy emoji kettő, ezért itt nem a
 * kódpontot számoljuk.
 */
function fitUtf16(value: string, max: number): string {
  const normalized = value.replace(/\s+/g, ' ').trim()
  if (normalized.length <= max) {
    return normalized
  }
  let out = ''
  for (const char of normalized) {
    if (out.length + char.length > max) {
      break
    }
    out += char
  }
  return out.trimEnd()
}

/**
 * A Barion 3DS-dátumalakja: UTC, ezredmásodperccel, `Z` NÉLKÜL. A doksi
 * (PurchaseInformation, PayerAccountInformation) szövege: „In UTC Expected
 * format: "2019-06-27T07:15:51.327"". Az ISO-alak `Z` utótagja ezért kerül le.
 */
export function barionUtcTimestamp(date: Date): string {
  return date.toISOString().replace(/Z$/, '')
}

const DAY_MS = 24 * 60 * 60 * 1000

/**
 * A fiók kora → AccountCreationIndicator. Az értékkészlet a barion-web-php
 * Enumerations/ThreeDSecure/AccountCreationIndicator enumja (NoAccount,
 * CreatedDuringThisTransaction, LessThan30Days, Between30And60Days,
 * MoreThan60Days); a határok az enum-nevekből. Jövőbeli (órahibás)
 * létrehozási időnél a „friss" sáv megy ki, nem dobunk.
 */
export function accountCreationIndicatorFor(
  accountCreated: Date,
  now: Date,
): BarionAccountCreationIndicator {
  const ageDays = (now.getTime() - accountCreated.getTime()) / DAY_MS
  if (ageDays < 30) {
    return 'LessThan30Days'
  }
  if (ageDays <= 60) {
    return 'Between30And60Days'
  }
  return 'MoreThan60Days'
}

/**
 * Az utca + házszám legfeljebb három, egyenként 50 egységes sorra bontva
 * (Street, Street2, Street3). Szóhatáron vágunk, ha a sorban van szóköz;
 * különben keményen. A harmadik sor utáni maradék elvész: a 3DS-cím
 * kockázatelemzésre szolgál, a számla a teljes címet a rendelés snapshotjából
 * kapja.
 */
export function splitStreetLines(street: string): string[] {
  const lines: string[] = []
  let rest = Array.from(street.replace(/\s+/g, ' ').trim())
  while (rest.length > 0 && lines.length < BARION_BILLING_STREET_LINES) {
    const whole = rest.join('')
    if (whole.length <= BARION_BILLING_STREET_MAX) {
      lines.push(whole)
      break
    }
    // Hány kódpont fér a sorba UTF-16-ban mérve.
    let fit = 0
    let units = 0
    while (fit < rest.length && units + rest[fit].length <= BARION_BILLING_STREET_MAX) {
      units += rest[fit].length
      fit += 1
    }
    // Szóhatár: ha a következő kódpont szóköz, a teljes sor jó; különben az
    // utolsó szóközig vágunk (ha van a sorban).
    let cut = fit
    if (rest[fit] !== ' ') {
      const lastSpace = rest.slice(0, fit).lastIndexOf(' ')
      if (lastSpace > 0) {
        cut = lastSpace
      }
    }
    lines.push(rest.slice(0, cut).join('').trimEnd())
    rest = Array.from(rest.slice(cut).join('').trim())
  }
  return lines
}

function mapBillingAddress(input: StartPaymentBillingAddressInput): BarionBillingAddress {
  const [street, street2, street3] = splitStreetLines(input.street)
  const city = fitUtf16(input.city, BARION_BILLING_CITY_MAX)
  const zip = fitUtf16(input.zip, BARION_BILLING_ZIP_MAX)
  return {
    Country: input.country === 'HU' ? 'HU' : 'ZZ',
    ...(city.length > 0 ? { City: city } : {}),
    ...(zip.length > 0 ? { Zip: zip } : {}),
    ...(street !== undefined && street.length > 0 ? { Street: street } : {}),
    ...(street2 !== undefined && street2.length > 0 ? { Street2: street2 } : {}),
    ...(street3 !== undefined && street3.length > 0 ? { Street3: street3 } : {}),
  }
}

function mapPurchaseInformation(input: StartPaymentThreeDsInput): BarionPurchaseInformation {
  const email = input.deliveryEmailAddress.trim()
  return {
    DeliveryTimeframe: 'ElectronicDelivery',
    ...(email.length > 0 ? { DeliveryEmailAddress: email } : {}),
    ShippingAddressIndicator: 'DigitalGoods',
    PurchaseType: 'GoodsAndServicePurchase',
    PurchaseDate: barionUtcTimestamp(input.purchaseDate),
  }
}

function isValidDate(value: Date | null): value is Date {
  return value !== null && !Number.isNaN(value.getTime())
}

function mapPayerAccount(input: StartPaymentThreeDsInput): BarionPayerAccountInformation {
  const account = input.payerAccount
  if (account.kind === 'guest') {
    return { AccountCreationIndicator: 'NoAccount' }
  }
  const accountId = fitUtf16(account.accountId, BARION_ACCOUNT_ID_MAX)
  const created = isValidDate(account.accountCreated) ? account.accountCreated : null
  return {
    ...(accountId.length > 0 ? { AccountId: accountId } : {}),
    ...(created !== null
      ? {
          AccountCreated: barionUtcTimestamp(created),
          AccountCreationIndicator: accountCreationIndicatorFor(created, input.purchaseDate),
        }
      : {}),
  }
}

function mapItem(item: StartPaymentItemInput): BarionItem {
  const name = fitText(item.name, BARION_ITEM_NAME_MAX)
  const description = fitText(item.description, BARION_ITEM_DESCRIPTION_MAX)
  return {
    Name: name,
    Description: description.length > 0 ? description : fitText(name, BARION_ITEM_DESCRIPTION_MAX),
    Quantity: item.quantity,
    Unit: item.unit,
    UnitPrice: item.unitPrice,
    ItemTotal: item.itemTotal,
    ...(item.sku !== undefined ? { SKU: fitText(item.sku, BARION_ITEM_SKU_MAX) } : {}),
  }
}

function mapTransaction(
  transaction: StartPaymentTransactionInput,
  defaultPayee: string,
): BarionPaymentTransaction {
  return {
    POSTransactionId: transaction.posTransactionId,
    Payee: transaction.payee ?? defaultPayee,
    Total: transaction.total,
    Currency: 'HUF',
    ...(transaction.comment !== undefined ? { Comment: transaction.comment } : {}),
    Items: transaction.items.map(mapItem),
  }
}

/** A Start-kérés body-építése külön, tisztán tesztelhető függvényben. */
export function buildPaymentStartRequest(
  params: StartPaymentParams,
  config: BarionClientConfig,
): Omit<BarionPaymentStartRequest, 'POSKey'> {
  if (params.transactions.length === 0) {
    throw new Error('Barion Payment/Start: legalább egy tranzakció kötelező.')
  }

  if (params.recurring !== undefined) {
    if (!config.recurringEnabled) {
      throw new Error(
        'Barion Payment/Start: recurring-előkészítést kért a hívó, de a funkció ki van kapcsolva ' +
          "(BARION_RECURRING_ENABLED !== 'true'). Kapcsold be a flaget, vagy ne add meg a recurring-paramétert.",
      )
    }
    if (params.recurring.initiateRecurrence && !params.recurring.recurrenceId) {
      throw new Error(
        'Barion Payment/Start: initiateRecurrence esetén a recurrenceId megadása kötelező.',
      )
    }
  }

  const cardHolderNameHint = cardHolderNameHintFor(params.cardHolderNameHint)
  const orderNumber =
    params.orderNumber !== undefined ? fitText(params.orderNumber, BARION_ORDER_NUMBER_MAX) : ''
  const threeDs = barionSend3dsEnabled() ? params.threeDs : undefined

  return {
    PaymentType: 'Immediate',
    GuestCheckOut: true,
    FundingSources: ['All'],
    Locale: 'hu-HU',
    Currency: 'HUF',
    PaymentWindow: params.paymentWindow ?? BARION_DEFAULT_PAYMENT_WINDOW,
    PaymentRequestId: params.paymentRequestId,
    ...(orderNumber.length > 0 ? { OrderNumber: orderNumber } : {}),
    ...(params.payerHint !== undefined ? { PayerHint: params.payerHint } : {}),
    ...(cardHolderNameHint !== undefined ? { CardHolderNameHint: cardHolderNameHint } : {}),
    RedirectUrl: params.redirectUrl,
    CallbackUrl: params.callbackUrl,
    Transactions: params.transactions.map((transaction) =>
      mapTransaction(transaction, config.payeeEmail),
    ),
    ...(threeDs !== undefined
      ? {
          BillingAddress: mapBillingAddress(threeDs.billingAddress),
          PurchaseInformation: mapPurchaseInformation(threeDs),
          PayerAccountInformation: mapPayerAccount(threeDs),
          // SOHA nem 'NoChallengeNeeded': a docs szerint ott „the liability is
          // on the merchant" (ChallengePreference). A NoPreference-nél a
          // felelősség a kártyakibocsátóé, a 3DS-ről a Barion dönt.
          ChallengePreference: 'NoPreference',
        }
      : {}),
    ...(params.recurring?.initiateRecurrence
      ? { InitiateRecurrence: true, RecurrenceId: params.recurring.recurrenceId }
      : {}),
  }
}

/**
 * Fizetés indítása (Payment/Start v2). A válasz GatewayUrl-jére kell a vevőt
 * irányítani; a PaymentId-t a rendelésen rögzíti a hívó (orders.barionPaymentId).
 */
export async function startPayment(
  params: StartPaymentParams,
  config?: BarionClientConfig,
): Promise<BarionPaymentStartResponse> {
  const resolvedConfig = config ?? getBarionConfig()
  const request = buildPaymentStartRequest(params, resolvedConfig)
  const response = await barionPost<BarionPaymentStartResponse>(
    '/v2/Payment/Start',
    request,
    resolvedConfig,
  )
  // A PaymentId a Barionban kötőjeles és kötőjel nélküli alakban is előfordul;
  // a rendelésre a kanonikus alak kerül (guid.ts). GUID nélkül a fizetés nem
  // követhető, ezért ez érvénytelen válasz.
  const paymentId = canonicalBarionGuid(response.PaymentId)
  if (paymentId === null) {
    throw new BarionApiError({
      message: 'A Barion Start-válasz nem tartalmaz érvényes PaymentId-t.',
      kind: 'invalid_response',
      endpoint: 'POST /v2/Payment/Start',
    })
  }
  return {
    ...response,
    PaymentId: paymentId,
    ...(Array.isArray(response.Transactions)
      ? {
          Transactions: response.Transactions.map((transaction) => ({
            ...transaction,
            TransactionId: canonicalizeBarionGuid(transaction.TransactionId),
          })),
        }
      : {}),
  }
}
